### ISSUE TITLE
Bugs and improvements

### ISSUE THREAD

**Issue by darknessangelo** [Geigerkind/ModifiedPowerAurasTBC#4] opened 2017-05-12 17:26 UTC
First of all I want to thank You for this addon. You did a great job! Here are few bugs I found and a few suggestions to improve the addon.

**Bugs**
1.) If You create some auras and reconect, auras works, but they didn't show up in a aura menu.
2.) If You add some auras and delete all of auras after and want to add some new ones, You have to klick several times when they show up in a menu. They are propably hidden.
3.) If You click on edit aura and change aura in a menu, You are still editing the first aura you opened. You have to click again on "edit aura".
4.) If You want to open RGB circle of colors in own timer setup, You can't move with a small circle and choose what color You want, but you have to simply click in some place.

**Suggestions for improvements**
1.) Add ability to write direct position of an aura.
2.) Add ability to write direct RGB color for timer color.
3.) Add ability to write direct path to sound.
4.) Add vertical grow of dynamic group.
5.) Add ability to make icons gray. For example for auras whoes not active at the moment.

Some of the abilities and buffs icons are missing, but didn't looking for all of them. For example Commanding Shout icon is missing. Perhaps create check box for using automaticaly buff/debuff icon.

**Comment by tdymel** [comment] 2017-06-07 14:32
Hey!
Wonderful suggestions. I have stopped the development on the addon though and I am just fixing some bugs now.

I fixed number 2. I could not reproduce 1.
3. Is not a bug, it is intended.
4. Im going to fix now.

Regarding features:
4. exist, you just have to change the orientation
5. Also exist. You gotta change the slide in the color picker
6. Click on the + you can add a path there. It will try to find an icon always if none is configured.

cheers!

Edit: 
Bug 1 is caused by bug 2. You gotta delete your saved variable or reassign the ids so that they are in order.

**Closed as completed by tdymel** 2017-06-07 14:32 UTC
